//http://www.danstools.com/javascript-obfuscate/index.php
var indexPage = "http://localhost/Proyects/SantaPublicidad/WebApp/";
var rollAdmin = 'Gerencia';
var OperatorFoldersAllowed = [indexPage+'Proyect/'];
var page = "http://localhost:8080";
var loginService = page+"/WebServicesPresupuestos/AppLoginAuthentication/login";
var validateLogin = page+"/WebServicesPresupuestos/AppLoginAuthentication/validation";
var logoutService = page+"/WebServicesPresupuestos/AppLoginAuthentication/logout";
var createUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/create";
var editUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/update";
var deleteUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/delete";
var userList = page+"/WebServicesPresupuestos/AppUsersCRUD/list";
var areaList = page+"/WebServicesPresupuestos/AppAreaCRUD/list";
var rollList = page+"/WebServicesPresupuestos/AppRollCRUD/list";
var createAreaService = page+"/WebServicesPresupuestos/AppAreaCRUD/create";
var providersList = page+"/WebServicesPresupuestos/AppProviderCRUD/list";
var clientList = page+"/WebServicesPresupuestos/"; //falta
var createCountryService = page+'/WebServicesPresupuestos/AppCountryCRUD/create';
var countryListService = page+'/WebServicesPresupuestos/AppCountryCRUD/list';
var citysListService = page+'/WebServicesPresupuestos/AppCityCRUD/list';
var createCityService = page+'/WebServicesPresupuestos/AppCityCRUD/create';
var createProviderService = page+'/WebServicesPresupuestos/AppProviderCRUD/create';
var createAddressService = page+'/WebServicesPresupuestos/AppAddressCRUD/create';
var createContactService = page+'/WebServicesPresupuestos/AppContactCRUD/create';
var createProductServiceService = page+'/WebServicesPresupuestos/AppProductServiceCRUD/create';
