//http://www.danstools.com/javascript-obfuscate/index.php
var indexPage = "http://localhost/Proyects/SantaPublicidad/WebApp/";
var page = "http://localhost:8080";
var loginService = page+"/WebServicesPresupuestos/AppLoginAuthentication/login";
var validateLogin = page+"/WebServicesPresupuestos/AppLoginAuthentication/validation";
var logoutService = page+"/WebServicesPresupuestos/AppLoginAuthentication/logout";
var createUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/create";
var editUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/update";
var deleteUserService = page+"/WebServicesPresupuestos/AppUsersCRUD/delete";
var userList = page+"/WebServicesPresupuestos/AppUsersCRUD/list";
var areaList = page+"/WebServicesPresupuestos/AppAreaCRUD/list";
var rollList = page+"/WebServicesPresupuestos/AppRollCRUD/list";
var createAreaService = page+"/WebServicesPresupuestos/AppAreaCRUD/create";
var providersList = page+"/WebServicesPresupuestos/AppProviderCRUD/list";
var clientList = page+"/WebServicesPresupuestos/"; //falta
var createCountryService = page+'/WebServicesPresupuestos/AppCountryCRUD/create';
var countryListService = page+'/WebServicesPresupuestos/AppCountryCRUD/list';
var citysListService = page+'/WebServicesPresupuestos/AppCityCRUD/list';
var createCityService = page+'/WebServicesPresupuestos/AppCityCRUD/create';